services:
  _defaults:
    autowire: true
    autoconfigure: true

  SolidWork\ContaoHelpfulidBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection,ContaoHelpfulidBundle.php}